### ISSUE TITLE
[Mechanics] - Thrower missing chassis assembly

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-jordan#1]
The thrower should also be attached to the chassis to better judge if it is fitting into the robot.

**Comment by Akustav** [comment]
Based on the model I think the thrower motor is a little too low. When pulling the ball it, the robot can be raised up to 9mm. I would lift the motor around 6 mm and extend the C-shaped ramp to bring it closer to the ball that will be pulled into the thrower.

Image illustrates the balls motion:
![image](https://user-images.githubusercontent.com/5435954/134777473-123a963a-56f1-4c8f-8cb5-7dbbe1d7e57b.png)

**Comment by VORPENV** [comment]
Done

**Comment by Akustav** [comment]
Accidentally put a comment on another task but there is an issue with the internal ramp:

![image](https://user-images.githubusercontent.com/5435954/134945926-54ad7634-dddd-4a57-a304-02d75501f57c.png)

Maybe the sketch is a little off and takes a bad reference

**Comment by VORPENV** [comment]
The sketch is changed

**Comment by Akustav** [comment]
Good. I would change one thing and that is to add a chamfer to the front edge. This reduces the chance that something gets impaled while driving around: 
![image](https://user-images.githubusercontent.com/5435954/135151924-af9b1d8c-3e2b-4daa-b5d7-adb7e61db9ee.png)

**Comment by VORPENV** [comment]
Done

**Comment by maidlam** [comment]
Resolved
