### ISSUE TITLE
Image processing code duplicated

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-jordan#11]
Some of the image processing code is duplicated in main.py and image_calibration.py:

https://github.com/ut-robotics/picr21-team-jordan/blob/90ed4fd66dad2126e0791d80cd730da7ee57e18f/main_folder/main.py#L37

https://github.com/ut-robotics/picr21-team-jordan/blob/90ed4fd66dad2126e0791d80cd730da7ee57e18f/main_folder/image_calibration.py#L82

It would be better if image processing would be done in one place and in separate file. Image processing should be outside of the state machine. Only game logic should be in the state machine and states should use object locations from image processing.

**Comment by Leonid-98** [comment]
**fixed**, <br>state machine is now separate class

**Comment by ReikoR** [comment]
No duplication anymore.
