### ISSUE TITLE
Keep GUI code separate from other code

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-jordan#12]
Try to move GUI updating to separate functions. You could first call image and other processing functions and after that the functions that update the GUI. Also GUI could be made optional by enabling it with a command line argument when the program is started.

**Comment by Leonid-98** [comment]
**fixed**<br>
there is separate gui class

**Comment by ReikoR** [comment]
This code looks weird:
https://github.com/ut-robotics/picr21-team-jordan/blob/4987ebe3df4d488476baacbc978ce16e679b80f8/main_folder/image_getter.py#L105-L107

What is the purpose of it?

**Comment by Leonid-98** [comment]
> 
> 
> This code looks weird:
> 
> https://github.com/ut-robotics/picr21-team-jordan/blob/4987ebe3df4d488476baacbc978ce16e679b80f8/main_folder/image_getter.py#L105-L107
> 
> What is the purpose of it?

@ReikoR i forgot to delete this line, now its gone
