### ISSUE TITLE
[Mechanics] - Ramp spacers to close to ball

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-jordan#2]
The ball can hit the spacers holding everything together. This can create issues for the trowing.
![image](https://user-images.githubusercontent.com/5435954/134505813-b954fe7c-1bff-48ed-a852-c35377c31d90.png)

**Comment by Akustav** [comment]
This hole is still too close, I think: 
![image](https://user-images.githubusercontent.com/5435954/134777351-80999d6e-6269-4f8b-bbfb-32c9cf2c3977.png)

**Comment by VORPENV** [comment]
Position was changed

**Comment by Akustav** [comment]
Hey! The third (top most hole) seems to clip into the ball a little. You can make the distance of every hole equal. This guarantees that all of them stay far enoguh away from the trajectory of the ball.

**Comment by VORPENV** [comment]
Done

**Comment by maidlam** [comment]
Resolved
