### ISSUE TITLE
Do not create separate code for completing tasks

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-jordan#22]
[_mainboard_communication.py](https://github.com/ut-robotics/picr21-team-jordan/blob/c40053266bd363a28d650fd3adbbaea86fbb1d9f/main_folder/_mainboard_communication.py)

Tasks are to test the main functionality of the robot and give you a better idea of what the robot needs to do and in which order to implement the functionality. Tasks should build upon the previous tasks code.

You can do temporary modifications in your code to complete the task according to the task requirements, but you should not have separate code for it.

For example to complete the mainboard communication task with the current code, you could use/implement states for finding the ball or driving to the ball or any other state where the robot moves on the court.

**Comment by Leonid-98** [comment]
**fixed**
deleted mainboard_communication files
