### ISSUE TITLE
Serial port is opened every time new speeds are sent to mainboard

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-jordan#24]
https://github.com/ut-robotics/picr21-team-jordan/blob/b0aeef8138876d4ae275fab5b78f5c8cd555717f/main_folder/move_function.py#L24

Serial port should be opened only once when the code starts.

It's probably better to create a class for mainboard communication that stores the serial port instance for later use.

It's also better to keep omni-motion calculations separate from mainboard communication.

**Comment by Leonid-98** [comment]
**fixed**<br>
https://github.com/ut-robotics/picr21-team-jordan/blob/5ba7878f3f30b542db5018d997705efe433d6058/main_folder/robot_movement.py#L8-L20
https://github.com/ut-robotics/picr21-team-jordan/blob/5ba7878f3f30b542db5018d997705efe433d6058/main_folder/state_machine.py#L15-L23
