### ISSUE TITLE
Use enums

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-jordan#26]
https://github.com/ut-robotics/picr21-team-jordan/blob/b0aeef8138876d4ae275fab5b78f5c8cd555717f/main_folder/state_machine.py#L15

Instead of using strings for states, it would be less error prone to use an [enum](https://docs.python.org/3/library/enum.html).

For example:
```python
from enum import Enum

class State(Enum):
    FIND_BALL = 1
    GO_TO_BALL = 2
    
class StateMachine:
    def __init__(self):
        self.current_state = State.FIND_BALL
```

Then code would look like this:
```python
if self.current_state == State.FIND_BALL:
```

**Comment by Leonid-98** [comment]
**fixed**
https://github.com/ut-robotics/picr21-team-jordan/blob/5ba7878f3f30b542db5018d997705efe433d6058/main_folder/state_machine.py#L7-L12
