### ISSUE TITLE
[Mechanics] - how thick the front covers have to be

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-jordan#27]
Was wondering how thick this area should be:

![image](https://user-images.githubusercontent.com/5435954/139915262-4acb6761-c97e-4455-bf9a-c811f9a26bd2.png)

If it is structurally unimportant it could be made thinner to quicken up the printing of the wheel. Also the thickness should be a divisible of 0.3 or the layer height of the printer.

**Comment by VORPENV** [comment]
I've divided the thickness by approximate 1 mm from both sides

**Comment by Akustav** [comment]
OK
