### ISSUE TITLE
[Mechanics] - change way roller shafts are retained

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-jordan#28]
I would suggest changing the way how rollers sit inside the wheel housing. Currently you have 2 semicircles that enclose the shaft but you can encounter alignment issues due to the more complex matching between 2 moving semi-circles.

I would suggest a slot that is as deep as the shafts diameter and a flat surface retains this shaft in the housing.

A picture to illustrate:
![image](https://user-images.githubusercontent.com/5435954/139916234-05a35d9d-ed9b-4408-8a55-971195b4c149.png)

**Comment by VORPENV** [comment]
Do you mean that is it better to create the slot for the roller's shaft in one "semi-wheel" ? And the second "semi-wheel" will have this flat surface?

**Comment by Akustav** [comment]
A deep slot for the shaft is better than 2 half-circles retaining it. I would change the design to have a deep groove for the shaft and a flat surface that holds the roller in.

**Comment by Akustav** [comment]
Seems good
