### ISSUE TITLE
[Mechanics] - screw space

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-jordan#29]
This is more of a question and less of an issue but you need exact length socket set screws here. I hope you accounted for it.

![image](https://user-images.githubusercontent.com/5435954/139916892-a8221dad-5268-4952-8762-3e97fab213a7.png)

**Comment by VORPENV** [comment]
Now I created small holes for screws

**Comment by VORPENV** [comment]
I plan to use set screw, so I don't need such screw spaces
