### ISSUE TITLE
[Mechanics] - Weird spacer lengths

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-jordan#3]
Spacer sizing for these specific spacers is 11.6mm. They should most likely be 12mm
![image](https://user-images.githubusercontent.com/5435954/134506010-0f52326f-f2e4-4fd9-85e3-c7d5b1597750.png)

**Comment by Akustav** [comment]
Quick question: How will they be fastened to each other? Currently, all spacers are female-female. Will you have a long bolt in there or something else?

**Comment by VORPENV** [comment]
The middle spacers will be FF, other - FM. I don't know how exactly show it in the model

**Comment by Akustav** [comment]
You can have the spacers modelled out like that, so they are FF or MM. Then it is easy to see what you want to do. If you modify the spacer models on the sides we can close this issue.

**Comment by Akustav** [comment]
OK
