### ISSUE TITLE
Improve code structure

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-jordan#39]
Some suggestions:

1. Create separate file/class for camera.  Camera can return RGB and optionally depth frames.
2. Create separate file/class for image processing. Image processing functions from `ImageGetter` and `ImageCalibraion` should be moved into this class. Frame from camera can be given as an argument to image processor's processing method.
3. Object (balls, baskets) locations from image processing can be given to the state machine.
4. Image calibration can use camera and image processing classes.
5. `ImageGetter` class should have different name as it's the main class and probably should not inherit from `ImageCalibraion` class.

**Comment by Leonid-98** [comment]
@ReikoR 
I did as you said:
main class gets image (from `Camera` class), gets coordinates of the objects (using `ImageProcessing` class) and sends coordinates to the `StateMachine` class. Also, all game info is sent into `Gui `class. In main class i have also `SocketListener` as parallel to main thread. It sends all socket data to the list, and main class checks that list every iteration.

Pushed changes into `not_tested` branch
