### ISSUE TITLE
Too many typos

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-jordan#40]
Some examples:

https://github.com/ut-robotics/picr21-team-jordan/blob/9e5311730d60695c8be9be84ec046d4377a3e32b/main_folder/image_getter.py#L14-L19

ImageCalibraion -> ImageCalibration
apllyes -> applies
StateMahchine -> StateMachine

https://github.com/ut-robotics/picr21-team-jordan/blob/9e5311730d60695c8be9be84ec046d4377a3e32b/main_folder/image_getter.py#L59

interrurpt -> interrupt 
curent -> current

**Comment by Leonid-98** [comment]
@ReikoR fixed all typos with `code spell checker` extension

**Comment by ReikoR** [comment]
`class ImageCalibraion` should also be fixed.

**Comment by Leonid-98** [comment]
@ReikoR 
Fixed that exact typo, everything looks ok, and extension doesen't see any typos as well
