### ISSUE TITLE
Camera resource is opened but never closed

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-jordan#52]
https://github.com/ut-robotics/picr21-team-jordan/blob/2ab4613d39a6d57e361e7e64e6009ab22df023fe/main_folder/main.py#L25

You should close the camera even after an exception or similar is thrown. Currently it is closed after the while loop ends.

**Comment by Leonid-98** [comment]
@Akustav 
https://github.com/ut-robotics/picr21-team-jordan/blob/c8c0c9cda4c80c28e4c8290ae943c9211dc9dea1/main_folder/main.py#L96-L100
