### ISSUE TITLE
[Mechanics] - hole size wrong on motor mounts

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-jordan#58]
These holes in the motor points should be 2.5 mm since they will have threads.

![image](https://user-images.githubusercontent.com/5435954/146515708-1f803a94-66db-43b5-bdc0-9118594c047f.png)

**Comment by VORPENV** [comment]
Done

**Comment by Akustav** [comment]
I actually meant the other way around. Holes on this need to be 2.5mm 
![image](https://user-images.githubusercontent.com/5435954/146632736-56d0540d-ee87-49e7-9aa3-4eb57f9bc06f.png)

**Comment by VORPENV** [comment]
Done
