### ISSUE TITLE
[Mechanics] - way to remove battery may be problematic

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-jordan#63]
I am not sure but it can be that the camera might interfer with battery swapping here. Not sure of a good way to visualize it. Maybe you can slip it inside but not 100% sire.

![image](https://user-images.githubusercontent.com/5435954/146516856-23de2bef-79a8-4567-880d-632acba2f6af.png)

**Comment by VORPENV** [comment]
Will it change the angle position of the camera?

**Comment by Akustav** [comment]
This might not be an issue, I think the battery can be slipped inside. Just pointing it out since I am not 100% sure

**Comment by VORPENV** [comment]
Now everything is okay
