### ISSUE TITLE
Use WebSockets

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-jordan#65]
https://github.com/ut-robotics/picr21-team-jordan/blob/fc84323724f5fff3af8c989fcdce25333d1a9085/main_folder/socket_data_getter.py#L3

Regular sockets are not the same as WebSockets.

**Comment by Leonid-98** [comment]
https://github.com/ut-robotics/picr21-team-jordan/blob/cb56a2684ab24524bdd6e2c9cd77c0464b7f6a6d/main_folder/main.py#L99-L104
