### ISSUE TITLE
SocketDataGetter instance is named camera_image

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-jordan#66]
https://github.com/ut-robotics/picr21-team-jordan/blob/fc84323724f5fff3af8c989fcdce25333d1a9085/main_folder/main.py#L105-L108

Better name should be used.

And `pass` is not needed/should not be used at the end of a function.

**Comment by Leonid-98** [comment]
https://github.com/ut-robotics/picr21-team-jordan/blob/79880c195dfcbbf2ae8e234e2cfa73f5677db614/main_folder/main.py#L107-L118
