### ISSUE TITLE
Make server adress simpler to configure

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-jordan#70]
Currently it is hardcoded. You can make it as an method argument and declare it either in a conf file or as a constant in code.

https://github.com/ut-robotics/picr21-team-jordan/blob/79880c195dfcbbf2ae8e234e2cfa73f5677db614/main_folder/main.py#L99-L104

**Comment by Leonid-98** [comment]
https://github.com/ut-robotics/picr21-team-jordan/blob/1c7e760182998ac827b36f4b7fe85d34a82ac9da/main_folder/main.py#L103-L109
