### ISSUE TITLE
Encoder 1 signals connected incorrectly to MCU

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-jordan#73]
![image](https://user-images.githubusercontent.com/1595938/147588703-1aa4d11e-9d90-450c-be72-ba2dde38fe8c.png)

TIM1_CH1 is PA8 pin, not PA9
TIM1_CH2 is PA9 pin, not PA10

**Comment by valli96** [comment]
Thank you for finding this
