### ISSUE TITLE
USB connector needs to be closer to board edge

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-jordan#81]
![image](https://user-images.githubusercontent.com/1595938/147593392-7f2817b7-d526-437c-8644-8c4f7798a9af.png)

USB connector has downwards edge, that will interfere with the PCB.

Picture from another board:

![image](https://user-images.githubusercontent.com/1595938/147593572-8f675e1c-7b38-4aa2-8ad9-524383953cda.png)

**Comment by valli96** [comment]
I hope this is the correct distance from the edge

**Comment by ReikoR** [comment]
3D model on the footprint would help with that.

From another board it seems that around 1.6 mm from the slot hole to board edge might be the max:

![image](https://user-images.githubusercontent.com/1595938/147655421-0bff4f97-4f43-4eb2-9bef-e65a04cadc6c.png)


You have right now 1.85mm, which is too much:

![image](https://user-images.githubusercontent.com/1595938/147655515-50ab062c-1aba-4d0f-a9b7-23862257df84.png)


The lines on Mechanical 13 layer are also useful:

![image](https://user-images.githubusercontent.com/1595938/147655658-eb3d2666-b852-48d7-a9c2-b964d8270fdd.png)

**Comment by valli96** [comment]
![grafik](https://user-images.githubusercontent.com/69409924/147810090-e5bc0ebb-3044-499a-b4f3-bd83692534a8.png)

I hope this will be fine
