### ISSUE TITLE
Fix DRC errors

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-jordan#86]
![image](https://user-images.githubusercontent.com/1595938/147655094-ff2e497a-3f93-447a-8160-8f036d00a696.png)

![image](https://user-images.githubusercontent.com/1595938/147655112-d946728e-50d2-4324-b6b4-1ed906c98a80.png)

**Comment by ReikoR** [comment]
Try to fix USB footprint. For some reason there is hole inside the slot in original footprint. The hole can be deleted.

![image](https://user-images.githubusercontent.com/1595938/147812123-2068906a-7a8f-4078-a8f9-b5990010c003.png)

**Comment by valli96** [comment]
![grafik](https://user-images.githubusercontent.com/69409924/147816133-58255e90-7c20-443f-a67b-759a1644b0a3.png)
If I move the USB too far to the edge, I get some DRC error

**Comment by ReikoR** [comment]
This line can be aligned with board edge:

![image](https://user-images.githubusercontent.com/1595938/147819660-8da87ce2-8fb5-4a7a-a8ef-25c316bed82a.png)

To fix Hole Size Constraint Violations, increase Maximum value in HoleSize rule:

![image](https://user-images.githubusercontent.com/1595938/147819740-1a359688-b7bc-4fff-a857-66860713a368.png)

[JLCPCB Capabilities](https://jlcpcb.com/capabilities/Capabilities):
Drill Hole Size: 0.20mm- 6.30mm

**Comment by valli96** [comment]
![grafik](https://user-images.githubusercontent.com/69409924/147842209-1d12e140-9d1b-42e1-a09b-483f7eb5ee67.png)
If I aligned  the connector with the board edge, I have a distance of 2.1mm

**Comment by ReikoR** [comment]
For issue #81, I measured distance from the edge of the slot, not from the center.

![image](https://user-images.githubusercontent.com/1595938/147655421-0bff4f97-4f43-4eb2-9bef-e65a04cadc6c.png)
