### ISSUE TITLE
Move ESD protection closer to USB connector

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-jordan#88]
Having ESD protection closer helps to avoid ESD spikes from propagating to other components.

![image](https://user-images.githubusercontent.com/1595938/147812481-59dab6eb-d1ea-42be-b311-579fa701ff88.png)

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/147820110-02bdcf04-a285-4927-bf50-58318c740fca.png)


Rotating the ESD protection component would help to improve the USB signal routing:

Something like this:

![image](https://user-images.githubusercontent.com/1595938/147820041-a8f73b46-ebb6-4e48-941d-0ed7b429f208.png)

**Comment by valli96** [comment]
![grafik](https://user-images.githubusercontent.com/69409924/147842147-17e855c0-be66-4589-954d-296a54a29e2a.png)
