### ISSUE TITLE
Avoid routing signals on GND layers

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-jordan#89]
![image](https://user-images.githubusercontent.com/1595938/147812642-6ce15c36-14a8-45c8-8f04-7f53d4203e63.png)

Splits in ground might cause electric fields to spread out, which might cause crosstalk on other signals.

Something like this would be better:

![image](https://user-images.githubusercontent.com/1595938/147812838-2bb92248-16ff-4168-b9b4-b9d455ea2cbd.png)

**Comment by valli96** [comment]
![grafik](https://user-images.githubusercontent.com/69409924/147816544-dbb5786f-8e54-4f04-98d5-83b6e50abeed.png)
Now it is routed through over the bottom layer

**Comment by ReikoR** [comment]
Now you are splitting up +16V and leaving narrow copper for high currents.

It's better to route nSLEEP near PGND polygon:

![image](https://user-images.githubusercontent.com/1595938/147820354-4d7fefd8-970d-4373-8081-cd90727eaf01.png)

**Comment by valli96** [comment]
![grafik](https://user-images.githubusercontent.com/69409924/147842159-f076ad6a-961a-4b3b-8c4b-2ac4ccf3aa8f.png)
