### ISSUE TITLE
Gerber files and Drill files export

### ISSUE THREAD

**Issue by valli96** [ut-robotics/picr21-team-jordan#90]
Altium has the function to export both Gerber files and drill files as one file. This should also be ok for JLC PCB. 

Are the settings right?
![grafik](https://user-images.githubusercontent.com/69409924/147863701-eebecd04-747c-420b-918e-19bed01907dc.png)

![grafik](https://user-images.githubusercontent.com/69409924/147863699-e0fae1bc-8f46-43a6-828e-3dff531c5d50.png)

**Comment by ReikoR** [comment]
X2 should probably work. I have used regular gerber (RS-274X).

From this [KiCad forum topic](https://forum.kicad.info/t/apologies-from-atommann-an-engineer-from-jlcpcb-about-gerber-x2-files-at-jlcpcb/26847/59), it seems JLCPCB is converting X2 format to RS-274X format for the software they are using.

For layers to plot you also need Mechanical 1 for board outline. You should not need keep-out and pad master layers.

**Comment by valli96** [comment]
I updated the zip file and added the Mechanical 1 layer
